/**
 * Copyright 2026 Abhishek Sinha (sinha@live.in)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, {
  useRef,
  useEffect,
  useMemo,
  Component,
  type ReactNode,
  type ErrorInfo,
} from "react";
import type { TelemetryConfig } from "../types/public";
import type { ResolvedConfig } from "../types/internal";
import { MetricName, SignalType } from "../types/internal";
import { ExporterType } from "../types/internal";
import { TelemetryContext, type TelemetryContextValue } from "./telemetryContext";
import { resolveConfig } from "./configManager";
import { SessionManager } from "./sessionManager";
import { SignalBus } from "./signalBus";
import { Pipeline } from "./pipeline";
import { ExporterManager } from "./exporterManager";
import { ConsoleExporter } from "../exporters/console/consoleExporter";
import { OtlpExporter } from "../exporters/otlp/otlpExporter";
import { ErrorCollector } from "../collectors/errorCollector";
import { NetworkCollector } from "../collectors/networkCollector";
import { LongTaskCollector } from "../collectors/longTaskCollector";
import { WebVitalsCollector } from "../collectors/webVitalsCollector";
import { MemoryCollector } from "../collectors/memoryCollector";
import { RageClickCollector } from "../collectors/rageClickCollector";
import { ResourceTimingCollector } from "../collectors/resourceTimingCollector";
import { isBrowser } from "../utils/browserEnvironment";
import { sanitiseUrl } from "../utils/sanitiseUrl";
import { getWallClockTime } from "../utils/timing";
import { Locale } from "../locale";
import { interpolate } from "../utils/interpolate";
import { RAPID_UNMOUNT_THRESHOLD_MS } from "../constants";

/**
 * Tracks which setup warnings have already been shown.
 * Module-level — resets on every server start (new JS bundle load).
 * Persists across page refreshes within the same server session.
 * Prevents duplicate output from React StrictMode double-mount.
 */
const shownWarnings = new Set<string>();

const warnOnce = (key: string, message: string): void => {
  if (shownWarnings.has(key)) return;
  shownWarnings.add(key);
  console.warn(message);
};

/** Props for TelemetryProvider */
export interface TelemetryProviderProps {
  /**
   * Static application config — import your telemetry.config.json here.
   * Accepts a plain JSON import directly — no cast required.
   * Generated by: npx react-telemetry-open init
   */
  readonly appConfig?: unknown;

  /**
   * Runtime config overrides — merged on top of appConfig.
   * Use for values known only at runtime:
   * sampling rate based on device, signals based on user consent, etc.
   *
   * Usage:
   *   <TelemetryProvider config={{ sampling: { rate: 0.1 } }}>
   */
  readonly config?: TelemetryConfig;

  readonly children: ReactNode;
}

/**
 * TelemetryErrorBoundary — catches all unhandled React render errors.
 * Implicitly wraps all children of TelemetryProvider.
 * Uses a class component because componentDidCatch is not available in hooks.
 */
class TelemetryErrorBoundary extends Component<
  {
    children: ReactNode;
    signalBus: SignalBus;
    config: ResolvedConfig;
    name?: string;
  },
  { hasError: boolean }
> {
  state = { hasError: false };

  static getDerivedStateFromError(): { hasError: boolean } {
    return { hasError: true };
  }

  componentDidCatch(caughtError: Error, errorInfo: ErrorInfo): void {
    // Wrapped in try-catch — our tracking code must NEVER crash the app
    try {
      this.props.signalBus.emit({
        type: SignalType.Log,
        name: MetricName.ReactError,
        timestamp: getWallClockTime(),
        route: typeof window !== "undefined"
          ? sanitiseUrl(window.location.pathname, this.props.config.privacy.stripQueryParams)
          : "",
        sessionId: "",
        attributes: {
          message: caughtError.message,
          stack: caughtError.stack ?? null,
          errorType: caughtError.constructor?.name ?? "Error",
          // React component stack — most valuable debugging signal
          componentStack: errorInfo.componentStack ?? null,
          boundaryName: this.props.name ?? "root",
        },
      });
    } catch {
      // Our error tracking threw — absolute worst case, silently ignore
      // App must not unmount due to our telemetry code
    }
  }

  render(): ReactNode {
    if (this.state.hasError) {
      return null; // Render nothing — app continues without the crashed subtree
    }
    return this.props.children;
  }
}

/**
 * TelemetryProvider — the root component for react-telemetry-open.
 *
 * Place at the top of your app, outside of routing:
 * ```tsx
 * <TelemetryProvider>
 *   <Router>
 *     <App />
 *   </Router>
 * </TelemetryProvider>
 * ```
 *
 * Boot sequence:
 *   Synchronous (before children render):
 *     1. ConfigManager resolves config
 *     2. SessionManager captures device metadata
 *     3. SignalBus initialised with pre-boot buffer
 *     4. ErrorCollector.initEarly() adds window error listeners
 *
 *   Async (after first paint via useEffect):
 *     5. Pipeline connects to Signal Bus and flushes pre-boot buffer
 *     6. ExporterManager initialised with configured exporters
 *     7. Automatic collectors boot (only those enabled in config)
 *     8. Telemetry singleton becomes available
 */
export const TelemetryProvider = ({
  appConfig,
  config: configProp,
  children,
}: TelemetryProviderProps): React.ReactElement => {
  // Step 1 — Config (synchronous, resolved once)
  // useRef ensures we only resolve config on first render, not on re-renders
  const resolvedConfigRef = useRef<ResolvedConfig | null>(null);
  if (resolvedConfigRef.current === null) {
    resolvedConfigRef.current = resolveConfig(appConfig, configProp);
  }
  const resolvedConfig = resolvedConfigRef.current;

  // Warn if running in non-browser environment (React Native, SSR without guards)
  if (!isBrowser() && typeof window !== "undefined") {
    if (resolvedConfig.debug) {
      console.warn(Locale.provider.nonBrowserEnvironment);
    }
  }

  // Warn if config prop changes after mount — changes are ignored
  const initialConfigPropRef = useRef(configProp);
  useEffect(() => {
    if (configProp !== initialConfigPropRef.current && resolvedConfig.debug) {
      console.warn(Locale.provider.configChangedAfterMount);
    }
  }, [configProp, resolvedConfig.debug]);

  // Step 2 — Session Manager (synchronous)
  const sessionManagerRef = useRef<SessionManager | null>(null);
  if (sessionManagerRef.current === null) {
    sessionManagerRef.current = new SessionManager(resolvedConfig.debug);
  }
  const sessionManager = sessionManagerRef.current;

  // Step 3 — Signal Bus (synchronous)
  const signalBusRef = useRef<SignalBus | null>(null);
  if (signalBusRef.current === null) {
    signalBusRef.current = new SignalBus(resolvedConfig.debug);
  }
  const signalBus = signalBusRef.current;

  // Track mount time for rapid unmount detection
  const mountTimestampRef = useRef(getWallClockTime());

  // Step 4 — ErrorCollector (synchronous, before children render)
  // Skip if Do Not Track is enabled — no collection at all
  const errorCollectorInitRef = useRef(false);
  if (!errorCollectorInitRef.current) {
    const dntActive =
      resolvedConfig.privacy.respectDoNotTrack &&
      typeof navigator !== "undefined" &&
      navigator.doNotTrack === "1";
    if (isBrowser() && !dntActive) {
      ErrorCollector.initEarly(signalBus, resolvedConfig);
    }
    errorCollectorInitRef.current = true;
  }

  // ExporterManager ref — created in useEffect, needed for flush
  const exporterManagerRef = useRef<ExporterManager | null>(null);

  // Stable context value — created once, never causes re-renders
  const contextValue = useMemo((): TelemetryContextValue => ({
    signalBus,
    config: resolvedConfig,
    sessionId: sessionManager.getSnapshot().sessionId,
    getCurrentRoute: () => {
      if (typeof window === "undefined") return "";
      return sanitiseUrl(
        window.location.pathname,
        resolvedConfig.privacy.stripQueryParams
      );
    },
    flush: async () => {
      if (exporterManagerRef.current) {
        await exporterManagerRef.current.flush([]);
      }
    },
    incrementPageViews: () => sessionManager.incrementPageViews(),
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }), []); // Empty deps — all values are stable for Provider lifetime

  // Steps 5-8 — Async boot (after first paint)
  useEffect(() => {
    if (!isBrowser()) return;

    // Do Not Track — check here (not in render) to avoid Rules of Hooks violation.
    // Provider always renders and provides Context so hooks work in children.
    // We simply skip booting any collectors when DNT is enabled.
    const doNotTrackEnabled =
      resolvedConfig.privacy.respectDoNotTrack &&
      typeof navigator !== "undefined" &&
      navigator.doNotTrack === "1";

    if (doNotTrackEnabled) return;

    // Re-initialise ErrorCollector here as well as in render phase.
    // React 18 StrictMode runs render ONCE but runs effects twice (mount → cleanup → remount).
    // The cleanup calls ErrorCollector.destroy() which removes window.onerror.
    // Since render doesn't run again, initEarly from render never re-fires.
    // Calling it here ensures the error handler is always active after remount.
    if (!ErrorCollector.initialised) {
      ErrorCollector.initEarly(signalBus, resolvedConfig);
    }

    // Use faster flush in console/development mode so events appear immediately.
    // In production with OTLP configured, original batch settings apply.
    const effectiveBatchConfig =
      resolvedConfig.exporter.type === ExporterType.Console
        ? { ...resolvedConfig.batch, size: 1, flushIntervalMs: 500 }
        : resolvedConfig.batch;
    const effectiveConfig = { ...resolvedConfig, batch: effectiveBatchConfig };

    // Step 5 — Pipeline
    const pipeline = new Pipeline(effectiveConfig, sessionManager);

    // Step 6 — Exporter Manager
    const exporterManager = new ExporterManager(resolvedConfig);
    exporterManagerRef.current = exporterManager;

    // Add configured exporters
    if (
      resolvedConfig.exporter.type === ExporterType.Otlp &&
      resolvedConfig.exporter.url
    ) {
      exporterManager.addExporter(new OtlpExporter(resolvedConfig));
    }

    // Always add console exporter in debug mode
    if (resolvedConfig.debug || resolvedConfig.exporter.type === ExporterType.Console) {
      exporterManager.addExporter(new ConsoleExporter());
    }

    pipeline.connect(exporterManager);

    // Connect Pipeline to Signal Bus — flushes pre-boot buffer
    signalBus.connectPipeline((event) => pipeline.process(event));

    // Step 7 — Boot automatic collectors (only if enabled in config)
    if (resolvedConfig.signals.network) {
      NetworkCollector.init(signalBus, resolvedConfig);
    }
    if (resolvedConfig.signals.longTasks) {
      LongTaskCollector.init(signalBus, resolvedConfig);
    }
    if (resolvedConfig.signals.webVitals) {
      WebVitalsCollector.init(signalBus, resolvedConfig);
    }
    if (resolvedConfig.signals.memory) {
      MemoryCollector.init(signalBus, resolvedConfig);
    }
    if (resolvedConfig.signals.interactions) {
      RageClickCollector.init(signalBus, resolvedConfig);
    }
    if (resolvedConfig.signals.resourceTiming) {
      ResourceTimingCollector.init(signalBus, resolvedConfig);
    }

    // Setup warnings — fire in development regardless of debug flag.
    // These are critical setup guidance, not verbose debug noise.
    // In production (MODE === "production") they are always silent.
    const isDev = (import.meta as { env?: { MODE?: string } }).env?.MODE !== "production";

    if (isDev) {
      const nameMissing = !resolvedConfig.app.name || resolvedConfig.app.name === "unknown-app";
      const versionMissing = resolvedConfig.app.version === "0.0.0";
      if (nameMissing || versionMissing) {
        warnOnce("missingAppConfig", Locale.provider.missingAppConfig);
      }
    }

    // Verbose debug warnings — only when debug: true
    if (resolvedConfig.debug) {
      if (
        (import.meta as { env?: { MODE?: string } }).env?.MODE === "production" &&
        resolvedConfig.exporter.type === ExporterType.Console
      ) {
        console.warn(Locale.provider.productionConsoleExporter);
      }
    }

    // Cleanup — runs in reverse dependency order
    return () => {
      const sessionDuration = getWallClockTime() - mountTimestampRef.current;
      if (sessionDuration < RAPID_UNMOUNT_THRESHOLD_MS && resolvedConfig.debug) {
        console.warn(
          interpolate(Locale.provider.rapidUnmountWarning, {
            duration: sessionDuration,
          })
        );
      }

      // 1. Flush remaining data first
      exporterManager.flushSync([]);

      // 2. Destroy collectors (stop collecting)
      ResourceTimingCollector.destroy();
      RageClickCollector.destroy();
      MemoryCollector.destroy();
      WebVitalsCollector.destroy();
      LongTaskCollector.destroy();
      NetworkCollector.destroy();

      // 3. ErrorCollector — reset ref for StrictMode remount
      errorCollectorInitRef.current = false;
      ErrorCollector.destroy();

      // 4. Pipeline (stop processing)
      pipeline.destroy();
      exporterManagerRef.current = null;

      // 5. Signal Bus last (stop all events)
      signalBus.removeAllListeners();
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []); // Empty deps — runs once on mount, cleanup on unmount

  return (
    <TelemetryContext.Provider value={contextValue}>
      <TelemetryErrorBoundary
        signalBus={signalBus}
        config={resolvedConfig}
        name="root"
      >
        {children}
      </TelemetryErrorBoundary>
    </TelemetryContext.Provider>
  );
};
